import { mkdir } from 'node:fs/promises';
import { execSync } from 'node:child_process';
import path from 'node:path';
const root = process.cwd();
const dist = path.join(root, 'dist', 'chrome');
const artifacts = path.join(root, 'artifacts');
await mkdir(artifacts, { recursive: true });
const zipPath = path.join(artifacts, 'mustela-v0.2.0-chrome.zip');
execSync(`cd '${dist}' && zip -qr '${zipPath}' .`);
console.log(`Created ${zipPath}`);
